export const countryList = [
    {
        label: 'Afghanistan',
        dialCode: '+93',
        ddiLength: 3,
        value: 'AF',
    },
    {
        label: 'Aland Islands',
        dialCode: '+358',
        ddiLength: 3,
        value: 'AX',
    },
    {
        label: 'Albania',
        dialCode: '+355',
        ddiLength: 3,
        value: 'AL',
    },
    {
        label: 'Algeria',
        dialCode: '+213',
        ddiLength: 3,
        value: 'DZ',
    },
    {
        label: 'AmericanSamoa',
        dialCode: '+1684',
        ddiLength: 3,
        value: 'AS',
    },
    {
        label: 'Andorra',
        dialCode: '+376',
        ddiLength: 3,
        value: 'AD',
    },
    {
        label: 'Angola',
        dialCode: '+244',
        ddiLength: 3,
        value: 'AO',
    },
    {
        label: 'Anguilla',
        dialCode: '+1264',
        ddiLength: 3,
        value: 'AI',
    },
    {
        label: 'Antarctica',
        dialCode: '+672',
        ddiLength: 3,
        value: 'AQ',
    },
    {
        label: 'Antigua and Barbuda',
        dialCode: '+1268',
        ddiLength: 3,
        value: 'AG',
    },
    {
        label: 'Argentina',
        dialCode: '+54',
        ddiLength: 3,
        value: 'AR',
    },
    {
        label: 'Armenia',
        dialCode: '+374',
        ddiLength: 3,
        value: 'AM',
    },
    {
        label: 'Aruba',
        dialCode: '+297',
        ddiLength: 3,
        value: 'AW',
    },
    {
        label: 'Australia',
        dialCode: '+61',
        ddiLength: 3,
        value: 'AU',
    },
    {
        label: 'Austria',
        dialCode: '+43',
        ddiLength: 3,
        value: 'AT',
    },
    {
        label: 'Azerbaijan',
        dialCode: '+994',
        ddiLength: 3,
        value: 'AZ',
    },
    {
        label: 'Bahamas',
        dialCode: '+1242',
        ddiLength: 3,
        value: 'BS',
    },
    {
        label: 'Bahrain',
        dialCode: '+973',
        ddiLength: 3,
        value: 'BH',
    },
    {
        label: 'Bangladesh',
        dialCode: '+880',
        ddiLength: 3,
        value: 'BD',
    },
    {
        label: 'Barbados',
        dialCode: '+1246',
        ddiLength: 3,
        value: 'BB',
    },
    {
        label: 'Belarus',
        dialCode: '+375',
        ddiLength: 3,
        value: 'BY',
    },
    {
        label: 'Belgium',
        dialCode: '+32',
        ddiLength: 3,
        value: 'BE',
    },
    {
        label: 'Belize',
        dialCode: '+501',
        ddiLength: 3,
        value: 'BZ',
    },
    {
        label: 'Benin',
        dialCode: '+229',
        ddiLength: 3,
        value: 'BJ',
    },
    {
        label: 'Bermuda',
        dialCode: '+1441',
        ddiLength: 3,
        value: 'BM',
    },
    {
        label: 'Bhutan',
        dialCode: '+975',
        ddiLength: 3,
        value: 'BT',
    },
    {
        label: 'Bolivia, Plurinational State of',
        dialCode: '+591',
        ddiLength: 3,
        value: 'BO',
    },
    {
        label: 'Bosnia and Herzegovina',
        dialCode: '+387',
        ddiLength: 3,
        value: 'BA',
    },
    {
        label: 'Botswana',
        dialCode: '+267',
        ddiLength: 3,
        value: 'BW',
    },
    {
        label: 'Brazil',
        dialCode: '+55',
        ddiLength: 3,
        value: 'BR',
    },
    {
        label: 'British Indian Ocean Territory',
        dialCode: '+246',
        ddiLength: 3,
        value: 'IO',
    },
    {
        label: 'Brunei Darussalam',
        dialCode: '+673',
        ddiLength: 3,
        value: 'BN',
    },
    {
        label: 'Bulgaria',
        dialCode: '+359',
        ddiLength: 3,
        value: 'BG',
    },
    {
        label: 'Burkina Faso',
        dialCode: '+226',
        ddiLength: 3,
        value: 'BF',
    },
    {
        label: 'Burundi',
        dialCode: '+257',
        ddiLength: 3,
        value: 'BI',
    },
    {
        label: 'Cambodia',
        dialCode: '+855',
        ddiLength: 3,
        value: 'KH',
    },
    {
        label: 'Cameroon',
        dialCode: '+237',
        ddiLength: 3,
        value: 'CM',
    },
    {
        label: 'Canada',
        dialCode: '+1',
        ddiLength: 3,
        value: 'CA',
    },
    {
        label: 'Cape Verde',
        dialCode: '+238',
        ddiLength: 3,
        value: 'CV',
    },
    {
        label: 'Cayman Islands',
        dialCode: '+ 345',
        ddiLength: 3,
        value: 'KY',
    },
    {
        label: 'Central African Republic',
        dialCode: '+236',
        ddiLength: 3,
        value: 'CF',
    },
    {
        label: 'Chad',
        dialCode: '+235',
        ddiLength: 3,
        value: 'TD',
    },
    {
        label: 'Chile',
        dialCode: '+56',
        ddiLength: 3,
        value: 'CL',
    },
    {
        label: 'China',
        dialCode: '+86',
        ddiLength: 3,
        value: 'CN',
    },
    {
        label: 'Christmas Island',
        dialCode: '+61',
        ddiLength: 3,
        value: 'CX',
    },
    {
        label: 'Cocos (Keeling) Islands',
        dialCode: '+61',
        ddiLength: 3,
        value: 'CC',
    },
    {
        label: 'Colombia',
        dialCode: '+57',
        ddiLength: 3,
        value: 'CO',
    },
    {
        label: 'Comoros',
        dialCode: '+269',
        ddiLength: 3,
        value: 'KM',
    },
    {
        label: 'Congo',
        dialCode: '+242',
        ddiLength: 3,
        value: 'CG',
    },
    {
        label: 'Congo, The Democratic Republic of the Congo',
        dialCode: '+243',
        ddiLength: 3,
        value: 'CD',
    },
    {
        label: 'Cook Islands',
        dialCode: '+682',
        ddiLength: 3,
        value: 'CK',
    },
    {
        label: 'Costa Rica',
        dialCode: '+506',
        ddiLength: 3,
        value: 'CR',
    },
    {
        label: "Cote d'Ivoire",
        dialCode: '+225',
        ddiLength: 3,
        value: 'CI',
    },
    {
        label: 'Croatia',
        dialCode: '+385',
        ddiLength: 3,
        value: 'HR',
    },
    {
        label: 'Cuba',
        dialCode: '+53',
        ddiLength: 3,
        value: 'CU',
    },
    {
        label: 'Cyprus',
        dialCode: '+357',
        ddiLength: 3,
        value: 'CY',
    },
    {
        label: 'Czech Republic',
        dialCode: '+420',
        ddiLength: 3,
        value: 'CZ',
    },
    {
        label: 'Denmark',
        dialCode: '+45',
        ddiLength: 3,
        value: 'DK',
    },
    {
        label: 'Djibouti',
        dialCode: '+253',
        ddiLength: 3,
        value: 'DJ',
    },
    {
        label: 'Dominica',
        dialCode: '+1767',
        ddiLength: 3,
        value: 'DM',
    },
    {
        label: 'Dominican Republic',
        dialCode: '+1849',
        ddiLength: 3,
        value: 'DO',
    },
    {
        label: 'Ecuador',
        dialCode: '+593',
        ddiLength: 3,
        value: 'EC',
    },
    {
        label: 'Egypt',
        dialCode: '+20',
        ddiLength: 3,
        value: 'EG',
    },
    {
        label: 'El Salvador',
        dialCode: '+503',
        ddiLength: 3,
        value: 'SV',
    },
    {
        label: 'Equatorial Guinea',
        dialCode: '+240',
        ddiLength: 3,
        value: 'GQ',
    },
    {
        label: 'Eritrea',
        dialCode: '+291',
        ddiLength: 3,
        value: 'ER',
    },
    {
        label: 'Estonia',
        dialCode: '+372',
        ddiLength: 3,
        value: 'EE',
    },
    {
        label: 'Ethiopia',
        dialCode: '+251',
        ddiLength: 3,
        value: 'ET',
    },
    {
        label: 'Falkland Islands (Malvinas)',
        dialCode: '+500',
        ddiLength: 3,
        value: 'FK',
    },
    {
        label: 'Faroe Islands',
        dialCode: '+298',
        ddiLength: 3,
        value: 'FO',
    },
    {
        label: 'Fiji',
        dialCode: '+679',
        ddiLength: 3,
        value: 'FJ',
    },
    {
        label: 'Finland',
        dialCode: '+358',
        ddiLength: 3,
        value: 'FI',
    },
    {
        label: 'France',
        dialCode: '+33',
        ddiLength: 3,
        value: 'FR',
    },
    {
        label: 'French Guiana',
        dialCode: '+594',
        ddiLength: 3,
        value: 'GF',
    },
    {
        label: 'French Polynesia',
        dialCode: '+689',
        ddiLength: 3,
        value: 'PF',
    },
    {
        label: 'Gabon',
        dialCode: '+241',
        ddiLength: 3,
        value: 'GA',
    },
    {
        label: 'Gambia',
        dialCode: '+220',
        ddiLength: 3,
        value: 'GM',
    },
    {
        label: 'Georgia',
        dialCode: '+995',
        ddiLength: 3,
        value: 'GE',
    },
    {
        label: 'Germany',
        dialCode: '+49',
        ddiLength: 3,
        value: 'DE',
    },
    {
        label: 'Ghana',
        dialCode: '+233',
        ddiLength: 3,
        value: 'GH',
    },
    {
        label: 'Gibraltar',
        dialCode: '+350',
        ddiLength: 3,
        value: 'GI',
    },
    {
        label: 'Greece',
        dialCode: '+30',
        ddiLength: 3,
        value: 'GR',
    },
    {
        label: 'Greenland',
        dialCode: '+299',
        ddiLength: 3,
        value: 'GL',
    },
    {
        label: 'Grenada',
        dialCode: '+1473',
        ddiLength: 3,
        value: 'GD',
    },
    {
        label: 'Guadeloupe',
        dialCode: '+590',
        ddiLength: 3,
        value: 'GP',
    },
    {
        label: 'Guam',
        dialCode: '+1671',
        ddiLength: 3,
        value: 'GU',
    },
    {
        label: 'Guatemala',
        dialCode: '+502',
        ddiLength: 3,
        value: 'GT',
    },
    {
        label: 'Guernsey',
        dialCode: '+44',
        ddiLength: 3,
        value: 'GG',
    },
    {
        label: 'Guinea',
        dialCode: '+224',
        ddiLength: 3,
        value: 'GN',
    },
    {
        label: 'Guinea-Bissau',
        dialCode: '+245',
        ddiLength: 3,
        value: 'GW',
    },
    {
        label: 'Guyana',
        dialCode: '+595',
        ddiLength: 3,
        value: 'GY',
    },
    {
        label: 'Haiti',
        dialCode: '+509',
        ddiLength: 3,
        value: 'HT',
    },
    {
        label: 'Holy See (Vatican City State)',
        dialCode: '+379',
        ddiLength: 3,
        value: 'VA',
    },
    {
        label: 'Honduras',
        dialCode: '+504',
        ddiLength: 3,
        value: 'HN',
    },
    {
        label: 'Hong Kong',
        dialCode: '+852',
        ddiLength: 3,
        value: 'HK',
    },
    {
        label: 'Hungary',
        dialCode: '+36',
        ddiLength: 3,
        value: 'HU',
    },
    {
        label: 'Iceland',
        dialCode: '+354',
        ddiLength: 3,
        value: 'IS',
    },
    {
        label: 'India',
        dialCode: '+91',
        ddiLength: 3,
        value: 'IN',
    },
    {
        label: 'Indonesia',
        dialCode: '+62',
        ddiLength: 3,
        value: 'ID',
    },
    {
        label: 'Iran, Islamic Republic of Persian Gulf',
        dialCode: '+98',
        ddiLength: 3,
        value: 'IR',
    },
    {
        label: 'Iraq',
        dialCode: '+964',
        ddiLength: 3,
        value: 'IQ',
    },
    {
        label: 'Ireland',
        dialCode: '+353',
        ddiLength: 3,
        value: 'IE',
    },
    {
        label: 'Isle of Man',
        dialCode: '+44',
        ddiLength: 3,
        value: 'IM',
    },
    {
        label: 'Israel',
        dialCode: '+972',
        ddiLength: 3,
        value: 'IL',
    },
    {
        label: 'Italy',
        dialCode: '+39',
        ddiLength: 3,
        value: 'IT',
    },
    {
        label: 'Jamaica',
        dialCode: '+1876',
        ddiLength: 3,
        value: 'JM',
    },
    {
        label: 'Japan',
        dialCode: '+81',
        ddiLength: 3,
        value: 'JP',
    },
    {
        label: 'Jersey',
        dialCode: '+44',
        ddiLength: 3,
        value: 'JE',
    },
    {
        label: 'Jordan',
        dialCode: '+962',
        ddiLength: 3,
        value: 'JO',
    },
    {
        label: 'Kazakhstan',
        dialCode: '+77',
        ddiLength: 3,
        value: 'KZ',
    },
    {
        label: 'Kenya',
        dialCode: '+254',
        ddiLength: 3,
        value: 'KE',
    },
    {
        label: 'Kiribati',
        dialCode: '+686',
        ddiLength: 3,
        value: 'KI',
    },
    {
        label: "Korea, Democratic People's Republic of Korea",
        dialCode: '+850',
        ddiLength: 3,
        value: 'KP',
    },
    {
        label: 'Korea, Republic of South Korea',
        dialCode: '+82',
        ddiLength: 3,
        value: 'KR',
    },
    {
        label: 'Kuwait',
        dialCode: '+965',
        ddiLength: 3,
        value: 'KW',
    },
    {
        label: 'Kyrgyzstan',
        dialCode: '+996',
        ddiLength: 3,
        value: 'KG',
    },
    {
        label: 'Laos',
        dialCode: '+856',
        ddiLength: 3,
        value: 'LA',
    },
    {
        label: 'Latvia',
        dialCode: '+371',
        ddiLength: 3,
        value: 'LV',
    },
    {
        label: 'Lebanon',
        dialCode: '+961',
        ddiLength: 3,
        value: 'LB',
    },
    {
        label: 'Lesotho',
        dialCode: '+266',
        ddiLength: 3,
        value: 'LS',
    },
    {
        label: 'Liberia',
        dialCode: '+231',
        ddiLength: 3,
        value: 'LR',
    },
    {
        label: 'Libyan Arab Jamahiriya',
        dialCode: '+218',
        ddiLength: 3,
        value: 'LY',
    },
    {
        label: 'Liechtenstein',
        dialCode: '+423',
        ddiLength: 3,
        value: 'LI',
    },
    {
        label: 'Lithuania',
        dialCode: '+370',
        ddiLength: 3,
        value: 'LT',
    },
    {
        label: 'Luxembourg',
        dialCode: '+352',
        ddiLength: 3,
        value: 'LU',
    },
    {
        label: 'Macao',
        dialCode: '+853',
        ddiLength: 3,
        value: 'MO',
    },
    {
        label: 'Macedonia',
        dialCode: '+389',
        ddiLength: 3,
        value: 'MK',
    },
    {
        label: 'Madagascar',
        dialCode: '+261',
        ddiLength: 3,
        value: 'MG',
    },
    {
        label: 'Malawi',
        dialCode: '+265',
        ddiLength: 3,
        value: 'MW',
    },
    {
        label: 'Malaysia',
        dialCode: '+60',
        ddiLength: 3,
        value: 'MY',
    },
    {
        label: 'Maldives',
        dialCode: '+960',
        ddiLength: 3,
        value: 'MV',
    },
    {
        label: 'Mali',
        dialCode: '+223',
        ddiLength: 3,
        value: 'ML',
    },
    {
        label: 'Malta',
        dialCode: '+356',
        ddiLength: 3,
        value: 'MT',
    },
    {
        label: 'Marshall Islands',
        dialCode: '+692',
        ddiLength: 3,
        value: 'MH',
    },
    {
        label: 'Martinique',
        dialCode: '+596',
        ddiLength: 3,
        value: 'MQ',
    },
    {
        label: 'Mauritania',
        dialCode: '+222',
        ddiLength: 3,
        value: 'MR',
    },
    {
        label: 'Mauritius',
        dialCode: '+230',
        ddiLength: 3,
        value: 'MU',
    },
    {
        label: 'Mayotte',
        dialCode: '+262',
        ddiLength: 3,
        value: 'YT',
    },
    {
        label: 'Mexico',
        dialCode: '+52',
        ddiLength: 3,
        value: 'MX',
    },
    {
        label: 'Micronesia, Federated States of Micronesia',
        dialCode: '+691',
        ddiLength: 3,
        value: 'FM',
    },
    {
        label: 'Moldova',
        dialCode: '+373',
        ddiLength: 3,
        value: 'MD',
    },
    {
        label: 'Monaco',
        dialCode: '+377',
        ddiLength: 3,
        value: 'MC',
    },
    {
        label: 'Mongolia',
        dialCode: '+976',
        ddiLength: 3,
        value: 'MN',
    },
    {
        label: 'Montenegro',
        dialCode: '+382',
        ddiLength: 3,
        value: 'ME',
    },
    {
        label: 'Montserrat',
        dialCode: '+1664',
        ddiLength: 3,
        value: 'MS',
    },
    {
        label: 'Morocco',
        dialCode: '+212',
        ddiLength: 3,
        value: 'MA',
    },
    {
        label: 'Mozambique',
        dialCode: '+258',
        ddiLength: 3,
        value: 'MZ',
    },
    {
        label: 'Myanmar',
        dialCode: '+95',
        ddiLength: 3,
        value: 'MM',
    },
    {
        label: 'Namibia',
        dialCode: '+264',
        ddiLength: 3,
        value: 'NA',
    },
    {
        label: 'Nauru',
        dialCode: '+674',
        ddiLength: 3,
        value: 'NR',
    },
    {
        label: 'Nepal',
        dialCode: '+977',
        ddiLength: 3,
        value: 'NP',
    },
    {
        label: 'Netherlands',
        dialCode: '+31',
        ddiLength: 3,
        value: 'NL',
    },
    {
        label: 'Netherlands Antilles',
        dialCode: '+599',
        ddiLength: 3,
        value: 'AN',
    },
    {
        label: 'New Caledonia',
        dialCode: '+687',
        ddiLength: 3,
        value: 'NC',
    },
    {
        label: 'New Zealand',
        dialCode: '+64',
        ddiLength: 3,
        value: 'NZ',
    },
    {
        label: 'Nicaragua',
        dialCode: '+505',
        ddiLength: 3,
        value: 'NI',
    },
    {
        label: 'Niger',
        dialCode: '+227',
        ddiLength: 3,
        value: 'NE',
    },
    {
        label: 'Nigeria',
        dialCode: '+234',
        ddiLength: 3,
        value: 'NG',
    },
    {
        label: 'Niue',
        dialCode: '+683',
        ddiLength: 3,
        value: 'NU',
    },
    {
        label: 'Norfolk Island',
        dialCode: '+672',
        ddiLength: 3,
        value: 'NF',
    },
    {
        label: 'Northern Mariana Islands',
        dialCode: '+1670',
        ddiLength: 3,
        value: 'MP',
    },
    {
        label: 'Norway',
        dialCode: '+47',
        ddiLength: 3,
        value: 'NO',
    },
    {
        label: 'Oman',
        dialCode: '+968',
        ddiLength: 3,
        value: 'OM',
    },
    {
        label: 'Pakistan',
        dialCode: '+92',
        ddiLength: 3,
        value: 'PK',
    },
    {
        label: 'Palau',
        dialCode: '+680',
        ddiLength: 3,
        value: 'PW',
    },
    {
        label: 'Palestinian Territory, Occupied',
        dialCode: '+970',
        ddiLength: 3,
        value: 'PS',
    },
    {
        label: 'Panama',
        dialCode: '+507',
        ddiLength: 3,
        value: 'PA',
    },
    {
        label: 'Papua New Guinea',
        dialCode: '+675',
        ddiLength: 3,
        value: 'PG',
    },
    {
        label: 'Paraguay',
        dialCode: '+595',
        ddiLength: 3,
        value: 'PY',
    },
    {
        label: 'Peru',
        dialCode: '+51',
        ddiLength: 3,
        value: 'PE',
    },
    {
        label: 'Philippines',
        dialCode: '+63',
        ddiLength: 3,
        value: 'PH',
    },
    {
        label: 'Pitcairn',
        dialCode: '+872',
        ddiLength: 3,
        value: 'PN',
    },
    {
        label: 'Poland',
        dialCode: '+48',
        ddiLength: 3,
        value: 'PL',
    },
    {
        label: 'Portugal',
        dialCode: '+351',
        ddiLength: 3,
        value: 'PT',
    },
    {
        label: 'Puerto Rico',
        dialCode: '+1939',
        ddiLength: 3,
        value: 'PR',
    },
    {
        label: 'Qatar',
        dialCode: '+974',
        ddiLength: 3,
        value: 'QA',
    },
    {
        label: 'Romania',
        dialCode: '+40',
        ddiLength: 3,
        value: 'RO',
    },
    {
        label: 'Russia',
        dialCode: '+7',
        ddiLength: 3,
        value: 'RU',
    },
    {
        label: 'Rwanda',
        dialCode: '+250',
        ddiLength: 3,
        value: 'RW',
    },
    {
        label: 'Reunion',
        dialCode: '+262',
        ddiLength: 3,
        value: 'RE',
    },
    {
        label: 'Saint Barthelemy',
        dialCode: '+590',
        ddiLength: 3,
        value: 'BL',
    },
    {
        label: 'Saint Helena, Ascension and Tristan Da Cunha',
        dialCode: '+290',
        ddiLength: 3,
        value: 'SH',
    },
    {
        label: 'Saint Kitts and Nevis',
        dialCode: '+1869',
        ddiLength: 3,
        value: 'KN',
    },
    {
        label: 'Saint Lucia',
        dialCode: '+1758',
        ddiLength: 3,
        value: 'LC',
    },
    {
        label: 'Saint Martin',
        dialCode: '+590',
        ddiLength: 3,
        value: 'MF',
    },
    {
        label: 'Saint Pierre and Miquelon',
        dialCode: '+508',
        ddiLength: 3,
        value: 'PM',
    },
    {
        label: 'Saint Vincent and the Grenadines',
        dialCode: '+1784',
        ddiLength: 3,
        value: 'VC',
    },
    {
        label: 'Samoa',
        dialCode: '+685',
        ddiLength: 3,
        value: 'WS',
    },
    {
        label: 'San Marino',
        dialCode: '+378',
        ddiLength: 3,
        value: 'SM',
    },
    {
        label: 'Sao Tome and Principe',
        dialCode: '+239',
        ddiLength: 3,
        value: 'ST',
    },
    {
        label: 'Saudi Arabia',
        dialCode: '+966',
        ddiLength: 3,
        value: 'SA',
    },
    {
        label: 'Senegal',
        dialCode: '+221',
        ddiLength: 3,
        value: 'SN',
    },
    {
        label: 'Serbia',
        dialCode: '+381',
        ddiLength: 3,
        value: 'RS',
    },
    {
        label: 'Seychelles',
        dialCode: '+248',
        ddiLength: 3,
        value: 'SC',
    },
    {
        label: 'Sierra Leone',
        dialCode: '+232',
        ddiLength: 3,
        value: 'SL',
    },
    {
        label: 'Singapore',
        dialCode: '+65',
        ddiLength: 3,
        value: 'SG',
    },
    {
        label: 'Slovakia',
        dialCode: '+421',
        ddiLength: 3,
        value: 'SK',
    },
    {
        label: 'Slovenia',
        dialCode: '+386',
        ddiLength: 3,
        value: 'SI',
    },
    {
        label: 'Solomon Islands',
        dialCode: '+677',
        ddiLength: 3,
        value: 'SB',
    },
    {
        label: 'Somalia',
        dialCode: '+252',
        ddiLength: 3,
        value: 'SO',
    },
    {
        label: 'South Africa',
        dialCode: '+27',
        ddiLength: 3,
        value: 'ZA',
    },
    {
        label: 'South Sudan',
        dialCode: '+211',
        ddiLength: 3,
        value: 'SS',
    },
    {
        label: 'South Georgia and the South Sandwich Islands',
        dialCode: '+500',
        ddiLength: 3,
        value: 'GS',
    },
    {
        label: 'Spain',
        dialCode: '+34',
        ddiLength: 3,
        value: 'ES',
    },
    {
        label: 'Sri Lanka',
        dialCode: '+94',
        ddiLength: 3,
        value: 'LK',
    },
    {
        label: 'Sudan',
        dialCode: '+249',
        ddiLength: 3,
        value: 'SD',
    },
    {
        label: 'Suriname',
        dialCode: '+597',
        ddiLength: 3,
        value: 'SR',
    },
    {
        label: 'Svalbard and Jan Mayen',
        dialCode: '+47',
        ddiLength: 3,
        value: 'SJ',
    },
    {
        label: 'Swaziland',
        dialCode: '+268',
        ddiLength: 3,
        value: 'SZ',
    },
    {
        label: 'Sweden',
        dialCode: '+46',
        ddiLength: 3,
        value: 'SE',
    },
    {
        label: 'Switzerland',
        dialCode: '+41',
        ddiLength: 3,
        value: 'CH',
    },
    {
        label: 'Syrian Arab Republic',
        dialCode: '+963',
        ddiLength: 3,
        value: 'SY',
    },
    {
        label: 'Taiwan',
        dialCode: '+886',
        ddiLength: 3,
        value: 'TW',
    },
    {
        label: 'Tajikistan',
        dialCode: '+992',
        ddiLength: 3,
        value: 'TJ',
    },
    {
        label: 'Tanzania, United Republic of Tanzania',
        dialCode: '+255',
        ddiLength: 3,
        value: 'TZ',
    },
    {
        label: 'Thailand',
        dialCode: '+66',
        ddiLength: 3,
        value: 'TH',
    },
    {
        label: 'Timor-Leste',
        dialCode: '+670',
        ddiLength: 3,
        value: 'TL',
    },
    {
        label: 'Togo',
        dialCode: '+228',
        ddiLength: 3,
        value: 'TG',
    },
    {
        label: 'Tokelau',
        dialCode: '+690',
        ddiLength: 3,
        value: 'TK',
    },
    {
        label: 'Tonga',
        dialCode: '+676',
        ddiLength: 3,
        value: 'TO',
    },
    {
        label: 'Trinidad and Tobago',
        dialCode: '+1868',
        ddiLength: 3,
        value: 'TT',
    },
    {
        label: 'Tunisia',
        dialCode: '+216',
        ddiLength: 3,
        value: 'TN',
    },
    {
        label: 'Turkey',
        dialCode: '+90',
        ddiLength: 3,
        value: 'TR',
    },
    {
        label: 'Turkmenistan',
        dialCode: '+993',
        ddiLength: 3,
        value: 'TM',
    },
    {
        label: 'Turks and Caicos Islands',
        dialCode: '+1649',
        ddiLength: 3,
        value: 'TC',
    },
    {
        label: 'Tuvalu',
        dialCode: '+688',
        ddiLength: 3,
        value: 'TV',
    },
    {
        label: 'Uganda',
        dialCode: '+256',
        ddiLength: 3,
        value: 'UG',
    },
    {
        label: 'Ukraine',
        dialCode: '+380',
        ddiLength: 3,
        value: 'UA',
    },
    {
        label: 'United Arab Emirates',
        dialCode: '+971',
        ddiLength: 3,
        value: 'AE',
    },
    {
        label: 'United Kingdom',
        dialCode: '+44',
        ddiLength: 3,
        value: 'GB',
    },
    {
        label: 'United States',
        dialCode: '+1',
        ddiLength: 3,
        value: 'US',
    },
    {
        label: 'Uruguay',
        dialCode: '+598',
        ddiLength: 3,
        value: 'UY',
    },
    {
        label: 'Uzbekistan',
        dialCode: '+998',
        ddiLength: 3,
        value: 'UZ',
    },
    {
        label: 'Vanuatu',
        dialCode: '+678',
        ddiLength: 3,
        value: 'VU',
    },
    {
        label: 'Venezuela, Bolivarian Republic of Venezuela',
        dialCode: '+58',
        ddiLength: 3,
        value: 'VE',
    },
    {
        label: 'Vietnam',
        dialCode: '+84',
        ddiLength: 3,
        value: 'VN',
    },
    {
        label: 'Virgin Islands, British',
        dialCode: '+1284',
        ddiLength: 3,
        value: 'VG',
    },
    {
        label: 'Virgin Islands, U.S.',
        dialCode: '+1340',
        ddiLength: 3,
        value: 'VI',
    },
    {
        label: 'Wallis and Futuna',
        dialCode: '+681',
        ddiLength: 3,
        value: 'WF',
    },
    {
        label: 'Yemen',
        dialCode: '+967',
        ddiLength: 3,
        value: 'YE',
    },
    {
        label: 'Zambia',
        dialCode: '+260',
        ddiLength: 3,
        value: 'ZM',
    },
    {
        label: 'Zimbabwe',
        dialCode: '+263',
        ddiLength: 3,
        value: 'ZW',
    },
]