/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { ResponseAccountUserDto } from './ResponseAccountUserDto';
import {
    ResponseAccountUserDtoFromJSON,
    ResponseAccountUserDtoFromJSONTyped,
    ResponseAccountUserDtoToJSON,
} from './ResponseAccountUserDto';

/**
 * 
 * @export
 * @interface AccountsUserResponse
 */
export interface AccountsUserResponse {
    /**
     * 
     * @type {Array<ResponseAccountUserDto>}
     * @memberof AccountsUserResponse
     */
    data: Array<ResponseAccountUserDto>;
    /**
     * 
     * @type {PageInfo}
     * @memberof AccountsUserResponse
     */
    pageInfo: PageInfo | null;
}

/**
 * Check if a given object implements the AccountsUserResponse interface.
 */
export function instanceOfAccountsUserResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pageInfo" in value;

    return isInstance;
}

export function AccountsUserResponseFromJSON(json: any): AccountsUserResponse {
    return AccountsUserResponseFromJSONTyped(json, false);
}

export function AccountsUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ResponseAccountUserDtoFromJSON)),
        'pageInfo': PageInfoFromJSON(json['pageInfo']),
    };
}

export function AccountsUserResponseToJSON(value?: AccountsUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ResponseAccountUserDtoToJSON)),
        'pageInfo': PageInfoToJSON(value.pageInfo),
    };
}

