/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { ResponseAccountDto } from './ResponseAccountDto';
import {
    ResponseAccountDtoFromJSON,
    ResponseAccountDtoFromJSONTyped,
    ResponseAccountDtoToJSON,
} from './ResponseAccountDto';

/**
 * 
 * @export
 * @interface AccountsResponse
 */
export interface AccountsResponse {
    /**
     * 
     * @type {Array<ResponseAccountDto>}
     * @memberof AccountsResponse
     */
    data: Array<ResponseAccountDto>;
    /**
     * 
     * @type {PageInfo}
     * @memberof AccountsResponse
     */
    pageInfo: PageInfo | null;
}

/**
 * Check if a given object implements the AccountsResponse interface.
 */
export function instanceOfAccountsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pageInfo" in value;

    return isInstance;
}

export function AccountsResponseFromJSON(json: any): AccountsResponse {
    return AccountsResponseFromJSONTyped(json, false);
}

export function AccountsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ResponseAccountDtoFromJSON)),
        'pageInfo': PageInfoFromJSON(json['pageInfo']),
    };
}

export function AccountsResponseToJSON(value?: AccountsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ResponseAccountDtoToJSON)),
        'pageInfo': PageInfoToJSON(value.pageInfo),
    };
}

