/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountInitialSubscribe
 */
export interface AccountInitialSubscribe {
    /**
     * The corporate name of the account
     * @type {string}
     * @memberof AccountInitialSubscribe
     */
    name: string;
    /**
     * The document number of the account
     * @type {string}
     * @memberof AccountInitialSubscribe
     */
    document: string;
}

/**
 * Check if a given object implements the AccountInitialSubscribe interface.
 */
export function instanceOfAccountInitialSubscribe(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "document" in value;

    return isInstance;
}

export function AccountInitialSubscribeFromJSON(json: any): AccountInitialSubscribe {
    return AccountInitialSubscribeFromJSONTyped(json, false);
}

export function AccountInitialSubscribeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountInitialSubscribe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'document': json['document'],
    };
}

export function AccountInitialSubscribeToJSON(value?: AccountInitialSubscribe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'document': value.document,
    };
}

