/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordOtpDto
 */
export interface ChangePasswordOtpDto {
    /**
     * Senha OTP
     * @type {string}
     * @memberof ChangePasswordOtpDto
     */
    number: string;
    /**
     * HASH
     * @type {string}
     * @memberof ChangePasswordOtpDto
     */
    hash: string;
    /**
     * Nova senha para o usuário
     * @type {string}
     * @memberof ChangePasswordOtpDto
     */
    password: string;
}

/**
 * Check if a given object implements the ChangePasswordOtpDto interface.
 */
export function instanceOfChangePasswordOtpDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "hash" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function ChangePasswordOtpDtoFromJSON(json: any): ChangePasswordOtpDto {
    return ChangePasswordOtpDtoFromJSONTyped(json, false);
}

export function ChangePasswordOtpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordOtpDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'hash': json['hash'],
        'password': json['password'],
    };
}

export function ChangePasswordOtpDtoToJSON(value?: ChangePasswordOtpDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'hash': value.hash,
        'password': value.password,
    };
}

