/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEventTicketGuestDto
 */
export interface CreateEventTicketGuestDto {
    /**
     * ID do evento associado ao ticket (UUID)
     * @type {string}
     * @memberof CreateEventTicketGuestDto
     */
    eventId: string;
    /**
     * ID do ticket (UUID)
     * @type {string}
     * @memberof CreateEventTicketGuestDto
     */
    eventTicketId: string;
}

/**
 * Check if a given object implements the CreateEventTicketGuestDto interface.
 */
export function instanceOfCreateEventTicketGuestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eventId" in value;
    isInstance = isInstance && "eventTicketId" in value;

    return isInstance;
}

export function CreateEventTicketGuestDtoFromJSON(json: any): CreateEventTicketGuestDto {
    return CreateEventTicketGuestDtoFromJSONTyped(json, false);
}

export function CreateEventTicketGuestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEventTicketGuestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventId': json['eventId'],
        'eventTicketId': json['eventTicketId'],
    };
}

export function CreateEventTicketGuestDtoToJSON(value?: CreateEventTicketGuestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventId': value.eventId,
        'eventTicketId': value.eventTicketId,
    };
}

