/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOtpDto
 */
export interface CreateOtpDto {
    /**
     * Tipo OTP
     * @type {string}
     * @memberof CreateOtpDto
     */
    type: CreateOtpDtoTypeEnum;
    /**
     * Email
     * @type {string}
     * @memberof CreateOtpDto
     */
    userEmail: string;
}


/**
 * @export
 */
export const CreateOtpDtoTypeEnum = {
    Otp: 'OTP',
    Recovery: 'RECOVERY'
} as const;
export type CreateOtpDtoTypeEnum = typeof CreateOtpDtoTypeEnum[keyof typeof CreateOtpDtoTypeEnum];


/**
 * Check if a given object implements the CreateOtpDto interface.
 */
export function instanceOfCreateOtpDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "userEmail" in value;

    return isInstance;
}

export function CreateOtpDtoFromJSON(json: any): CreateOtpDto {
    return CreateOtpDtoFromJSONTyped(json, false);
}

export function CreateOtpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOtpDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'userEmail': json['userEmail'],
    };
}

export function CreateOtpDtoToJSON(value?: CreateOtpDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'userEmail': value.userEmail,
    };
}

