/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserInitialSubscribeClub } from './UserInitialSubscribeClub';
import {
    UserInitialSubscribeClubFromJSON,
    UserInitialSubscribeClubFromJSONTyped,
    UserInitialSubscribeClubToJSON,
} from './UserInitialSubscribeClub';

/**
 * 
 * @export
 * @interface CreateInitialSubscribeClubDto
 */
export interface CreateInitialSubscribeClubDto {
    /**
     * 
     * @type {UserInitialSubscribeClub}
     * @memberof CreateInitialSubscribeClubDto
     */
    user: UserInitialSubscribeClub;
}

/**
 * Check if a given object implements the CreateInitialSubscribeClubDto interface.
 */
export function instanceOfCreateInitialSubscribeClubDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function CreateInitialSubscribeClubDtoFromJSON(json: any): CreateInitialSubscribeClubDto {
    return CreateInitialSubscribeClubDtoFromJSONTyped(json, false);
}

export function CreateInitialSubscribeClubDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInitialSubscribeClubDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserInitialSubscribeClubFromJSON(json['user']),
    };
}

export function CreateInitialSubscribeClubDtoToJSON(value?: CreateInitialSubscribeClubDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserInitialSubscribeClubToJSON(value.user),
    };
}

