/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountInitialSubscribe } from './AccountInitialSubscribe';
import {
    AccountInitialSubscribeFromJSON,
    AccountInitialSubscribeFromJSONTyped,
    AccountInitialSubscribeToJSON,
} from './AccountInitialSubscribe';
import type { UserInitialSubscribe } from './UserInitialSubscribe';
import {
    UserInitialSubscribeFromJSON,
    UserInitialSubscribeFromJSONTyped,
    UserInitialSubscribeToJSON,
} from './UserInitialSubscribe';

/**
 * 
 * @export
 * @interface CreateInitialSubscribeDto
 */
export interface CreateInitialSubscribeDto {
    /**
     * 
     * @type {UserInitialSubscribe}
     * @memberof CreateInitialSubscribeDto
     */
    user: UserInitialSubscribe;
    /**
     * 
     * @type {AccountInitialSubscribe}
     * @memberof CreateInitialSubscribeDto
     */
    account: AccountInitialSubscribe;
}

/**
 * Check if a given object implements the CreateInitialSubscribeDto interface.
 */
export function instanceOfCreateInitialSubscribeDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "account" in value;

    return isInstance;
}

export function CreateInitialSubscribeDtoFromJSON(json: any): CreateInitialSubscribeDto {
    return CreateInitialSubscribeDtoFromJSONTyped(json, false);
}

export function CreateInitialSubscribeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInitialSubscribeDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserInitialSubscribeFromJSON(json['user']),
        'account': AccountInitialSubscribeFromJSON(json['account']),
    };
}

export function CreateInitialSubscribeDtoToJSON(value?: CreateInitialSubscribeDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserInitialSubscribeToJSON(value.user),
        'account': AccountInitialSubscribeToJSON(value.account),
    };
}

