/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAddressDto
 */
export interface CreateAddressDto {
    /**
     * 
     * @type {string}
     * @memberof CreateAddressDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressDto
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressDto
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressDto
     */
    country: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAddressDto
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressDto
     */
    label: string;
}

/**
 * Check if a given object implements the CreateAddressDto interface.
 */
export function instanceOfCreateAddressDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "street" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "isActive" in value;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function CreateAddressDtoFromJSON(json: any): CreateAddressDto {
    return CreateAddressDtoFromJSONTyped(json, false);
}

export function CreateAddressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAddressDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'street': json['street'],
        'city': json['city'],
        'state': json['state'],
        'country': json['country'],
        'isActive': json['isActive'],
        'label': json['label'],
    };
}

export function CreateAddressDtoToJSON(value?: CreateAddressDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'street': value.street,
        'city': value.city,
        'state': value.state,
        'country': value.country,
        'isActive': value.isActive,
        'label': value.label,
    };
}

