/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEventTicketDto
 */
export interface CreateEventTicketDto {
    /**
     * ID do evento associado ao ticket (UUID)
     * @type {string}
     * @memberof CreateEventTicketDto
     */
    eventId: string;
    /**
     * Nome do participante
     * @type {string}
     * @memberof CreateEventTicketDto
     */
    name: string;
    /**
     * Descrição do ingresso
     * @type {string}
     * @memberof CreateEventTicketDto
     */
    description: string;
    /**
     * Preço do ingresso
     * @type {number}
     * @memberof CreateEventTicketDto
     */
    price: number;
    /**
     * Preço antes do desconto
     * @type {number}
     * @memberof CreateEventTicketDto
     */
    priceBefore: number;
    /**
     * 
     * @type {string}
     * @memberof CreateEventTicketDto
     */
    status: CreateEventTicketDtoStatusEnum;
    /**
     * Cor do ingresso
     * @type {string}
     * @memberof CreateEventTicketDto
     */
    color?: string;
    /**
     * Número de convidados
     * @type {number}
     * @memberof CreateEventTicketDto
     */
    guest?: number;
}


/**
 * @export
 */
export const CreateEventTicketDtoStatusEnum = {
    Enable: 'ENABLE',
    Disable: 'DISABLE'
} as const;
export type CreateEventTicketDtoStatusEnum = typeof CreateEventTicketDtoStatusEnum[keyof typeof CreateEventTicketDtoStatusEnum];


/**
 * Check if a given object implements the CreateEventTicketDto interface.
 */
export function instanceOfCreateEventTicketDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eventId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "priceBefore" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function CreateEventTicketDtoFromJSON(json: any): CreateEventTicketDto {
    return CreateEventTicketDtoFromJSONTyped(json, false);
}

export function CreateEventTicketDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEventTicketDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventId': json['eventId'],
        'name': json['name'],
        'description': json['description'],
        'price': json['price'],
        'priceBefore': json['priceBefore'],
        'status': json['status'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'guest': !exists(json, 'guest') ? undefined : json['guest'],
    };
}

export function CreateEventTicketDtoToJSON(value?: CreateEventTicketDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventId': value.eventId,
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'priceBefore': value.priceBefore,
        'status': value.status,
        'color': value.color,
        'guest': value.guest,
    };
}

