/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteUserResponse
 */
export interface DeleteUserResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteUserResponse
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteUserResponse interface.
 */
export function instanceOfDeleteUserResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function DeleteUserResponseFromJSON(json: any): DeleteUserResponse {
    return DeleteUserResponseFromJSONTyped(json, false);
}

export function DeleteUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function DeleteUserResponseToJSON(value?: DeleteUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

