/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteAddressResponse
 */
export interface DeleteAddressResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteAddressResponse
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteAddressResponse interface.
 */
export function instanceOfDeleteAddressResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function DeleteAddressResponseFromJSON(json: any): DeleteAddressResponse {
    return DeleteAddressResponseFromJSONTyped(json, false);
}

export function DeleteAddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteAddressResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function DeleteAddressResponseToJSON(value?: DeleteAddressResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

