/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { ResponseDocumentDto } from './ResponseDocumentDto';
import {
    ResponseDocumentDtoFromJSON,
    ResponseDocumentDtoFromJSONTyped,
    ResponseDocumentDtoToJSON,
} from './ResponseDocumentDto';

/**
 * 
 * @export
 * @interface DocumentsResponse
 */
export interface DocumentsResponse {
    /**
     * 
     * @type {Array<ResponseDocumentDto>}
     * @memberof DocumentsResponse
     */
    data: Array<ResponseDocumentDto>;
    /**
     * 
     * @type {PageInfo}
     * @memberof DocumentsResponse
     */
    pageInfo: PageInfo | null;
}

/**
 * Check if a given object implements the DocumentsResponse interface.
 */
export function instanceOfDocumentsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pageInfo" in value;

    return isInstance;
}

export function DocumentsResponseFromJSON(json: any): DocumentsResponse {
    return DocumentsResponseFromJSONTyped(json, false);
}

export function DocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ResponseDocumentDtoFromJSON)),
        'pageInfo': PageInfoFromJSON(json['pageInfo']),
    };
}

export function DocumentsResponseToJSON(value?: DocumentsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ResponseDocumentDtoToJSON)),
        'pageInfo': PageInfoToJSON(value.pageInfo),
    };
}

