/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { ResponseEventTicketDto } from './ResponseEventTicketDto';
import {
    ResponseEventTicketDtoFromJSON,
    ResponseEventTicketDtoFromJSONTyped,
    ResponseEventTicketDtoToJSON,
} from './ResponseEventTicketDto';

/**
 * 
 * @export
 * @interface EventsTicketsResponse
 */
export interface EventsTicketsResponse {
    /**
     * 
     * @type {Array<ResponseEventTicketDto>}
     * @memberof EventsTicketsResponse
     */
    data: Array<ResponseEventTicketDto>;
    /**
     * 
     * @type {PageInfo}
     * @memberof EventsTicketsResponse
     */
    pageInfo: PageInfo | null;
}

/**
 * Check if a given object implements the EventsTicketsResponse interface.
 */
export function instanceOfEventsTicketsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pageInfo" in value;

    return isInstance;
}

export function EventsTicketsResponseFromJSON(json: any): EventsTicketsResponse {
    return EventsTicketsResponseFromJSONTyped(json, false);
}

export function EventsTicketsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsTicketsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ResponseEventTicketDtoFromJSON)),
        'pageInfo': PageInfoFromJSON(json['pageInfo']),
    };
}

export function EventsTicketsResponseToJSON(value?: EventsTicketsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ResponseEventTicketDtoToJSON)),
        'pageInfo': PageInfoToJSON(value.pageInfo),
    };
}

