/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseEventConfigDto } from './ResponseEventConfigDto';
import {
    ResponseEventConfigDtoFromJSON,
    ResponseEventConfigDtoFromJSONTyped,
    ResponseEventConfigDtoToJSON,
} from './ResponseEventConfigDto';

/**
 * 
 * @export
 * @interface EventConfigResponse
 */
export interface EventConfigResponse {
    /**
     * 
     * @type {ResponseEventConfigDto}
     * @memberof EventConfigResponse
     */
    data: ResponseEventConfigDto;
}

/**
 * Check if a given object implements the EventConfigResponse interface.
 */
export function instanceOfEventConfigResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function EventConfigResponseFromJSON(json: any): EventConfigResponse {
    return EventConfigResponseFromJSONTyped(json, false);
}

export function EventConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventConfigResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ResponseEventConfigDtoFromJSON(json['data']),
    };
}

export function EventConfigResponseToJSON(value?: EventConfigResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ResponseEventConfigDtoToJSON(value.data),
    };
}

