/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { ResponseEventParticipantDto } from './ResponseEventParticipantDto';
import {
    ResponseEventParticipantDtoFromJSON,
    ResponseEventParticipantDtoFromJSONTyped,
    ResponseEventParticipantDtoToJSON,
} from './ResponseEventParticipantDto';

/**
 * 
 * @export
 * @interface EventsParticipantsResponse
 */
export interface EventsParticipantsResponse {
    /**
     * 
     * @type {Array<ResponseEventParticipantDto>}
     * @memberof EventsParticipantsResponse
     */
    data: Array<ResponseEventParticipantDto>;
    /**
     * 
     * @type {PageInfo}
     * @memberof EventsParticipantsResponse
     */
    pageInfo: PageInfo | null;
}

/**
 * Check if a given object implements the EventsParticipantsResponse interface.
 */
export function instanceOfEventsParticipantsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pageInfo" in value;

    return isInstance;
}

export function EventsParticipantsResponseFromJSON(json: any): EventsParticipantsResponse {
    return EventsParticipantsResponseFromJSONTyped(json, false);
}

export function EventsParticipantsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsParticipantsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ResponseEventParticipantDtoFromJSON)),
        'pageInfo': PageInfoFromJSON(json['pageInfo']),
    };
}

export function EventsParticipantsResponseToJSON(value?: EventsParticipantsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ResponseEventParticipantDtoToJSON)),
        'pageInfo': PageInfoToJSON(value.pageInfo),
    };
}

