/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
} from './PageInfo';
import type { ResponseEventDto } from './ResponseEventDto';
import {
    ResponseEventDtoFromJSON,
    ResponseEventDtoFromJSONTyped,
    ResponseEventDtoToJSON,
} from './ResponseEventDto';

/**
 * 
 * @export
 * @interface EventsResponse
 */
export interface EventsResponse {
    /**
     * 
     * @type {Array<ResponseEventDto>}
     * @memberof EventsResponse
     */
    data: Array<ResponseEventDto>;
    /**
     * 
     * @type {PageInfo}
     * @memberof EventsResponse
     */
    pageInfo: PageInfo | null;
}

/**
 * Check if a given object implements the EventsResponse interface.
 */
export function instanceOfEventsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pageInfo" in value;

    return isInstance;
}

export function EventsResponseFromJSON(json: any): EventsResponse {
    return EventsResponseFromJSONTyped(json, false);
}

export function EventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ResponseEventDtoFromJSON)),
        'pageInfo': PageInfoFromJSON(json['pageInfo']),
    };
}

export function EventsResponseToJSON(value?: EventsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ResponseEventDtoToJSON)),
        'pageInfo': PageInfoToJSON(value.pageInfo),
    };
}

