/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginWithAccountDto
 */
export interface LoginWithAccountDto {
    /**
     * Account ID
     * @type {string}
     * @memberof LoginWithAccountDto
     */
    accountId: string;
}

/**
 * Check if a given object implements the LoginWithAccountDto interface.
 */
export function instanceOfLoginWithAccountDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;

    return isInstance;
}

export function LoginWithAccountDtoFromJSON(json: any): LoginWithAccountDto {
    return LoginWithAccountDtoFromJSONTyped(json, false);
}

export function LoginWithAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginWithAccountDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
    };
}

export function LoginWithAccountDtoToJSON(value?: LoginWithAccountDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
    };
}

