/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseOTPHashDTO
 */
export interface ResponseOTPHashDTO {
    /**
     * HASH
     * @type {string}
     * @memberof ResponseOTPHashDTO
     */
    hash: string;
}

/**
 * Check if a given object implements the ResponseOTPHashDTO interface.
 */
export function instanceOfResponseOTPHashDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hash" in value;

    return isInstance;
}

export function ResponseOTPHashDTOFromJSON(json: any): ResponseOTPHashDTO {
    return ResponseOTPHashDTOFromJSONTyped(json, false);
}

export function ResponseOTPHashDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOTPHashDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': json['hash'],
    };
}

export function ResponseOTPHashDTOToJSON(value?: ResponseOTPHashDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
    };
}

