/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDocumentResponseDto } from './UserDocumentResponseDto';
import {
    UserDocumentResponseDtoFromJSON,
    UserDocumentResponseDtoFromJSONTyped,
    UserDocumentResponseDtoToJSON,
} from './UserDocumentResponseDto';

/**
 * 
 * @export
 * @interface ResponseDocumentDto
 */
export interface ResponseDocumentDto {
    /**
     * ID do documento (UUID)
     * @type {string}
     * @memberof ResponseDocumentDto
     */
    id: string;
    /**
     * Número do documento
     * @type {string}
     * @memberof ResponseDocumentDto
     */
    number: string;
    /**
     * Tipo do documento
     * @type {string}
     * @memberof ResponseDocumentDto
     */
    type: string;
    /**
     * Path do documento no computador
     * @type {string}
     * @memberof ResponseDocumentDto
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseDocumentDto
     */
    status: ResponseDocumentDtoStatusEnum;
    /**
     * Data e hora da criação do documento
     * @type {Date}
     * @memberof ResponseDocumentDto
     */
    createdAt: Date;
    /**
     * Data e hora da última atualização no documento
     * @type {Date}
     * @memberof ResponseDocumentDto
     */
    updatedAt: Date;
    /**
     * Data e hora da exclusão do documento
     * @type {Date}
     * @memberof ResponseDocumentDto
     */
    deletedAt: Date;
    /**
     * 
     * @type {UserDocumentResponseDto}
     * @memberof ResponseDocumentDto
     */
    userDocument: UserDocumentResponseDto;
}


/**
 * @export
 */
export const ResponseDocumentDtoStatusEnum = {
    Sent: 'SENT',
    AwaitingVerification: 'AWAITING_VERIFICATION',
    Verified: 'VERIFIED'
} as const;
export type ResponseDocumentDtoStatusEnum = typeof ResponseDocumentDtoStatusEnum[keyof typeof ResponseDocumentDtoStatusEnum];


/**
 * Check if a given object implements the ResponseDocumentDto interface.
 */
export function instanceOfResponseDocumentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "filePath" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "deletedAt" in value;
    isInstance = isInstance && "userDocument" in value;

    return isInstance;
}

export function ResponseDocumentDtoFromJSON(json: any): ResponseDocumentDto {
    return ResponseDocumentDtoFromJSONTyped(json, false);
}

export function ResponseDocumentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseDocumentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'number': json['number'],
        'type': json['type'],
        'filePath': json['filePath'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': (new Date(json['deletedAt'])),
        'userDocument': UserDocumentResponseDtoFromJSON(json['userDocument']),
    };
}

export function ResponseDocumentDtoToJSON(value?: ResponseDocumentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'number': value.number,
        'type': value.type,
        'filePath': value.filePath,
        'status': value.status,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'deletedAt': (value.deletedAt.toISOString()),
        'userDocument': UserDocumentResponseDtoToJSON(value.userDocument),
    };
}

