/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseEventDto
 */
export interface ResponseEventDto {
    /**
     * ID do evento (UUID)
     * @type {string}
     * @memberof ResponseEventDto
     */
    id: string;
    /**
     * ID sequencial do evento
     * @type {number}
     * @memberof ResponseEventDto
     */
    sequential: number;
    /**
     * ID da conta associada ao evento (UUID)
     * @type {string}
     * @memberof ResponseEventDto
     */
    accountId: string;
    /**
     * ID do usuário associado ao evento (UUID)
     * @type {string}
     * @memberof ResponseEventDto
     */
    userId: string;
    /**
     * Nome do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    name: string;
    /**
     * Subtítulo do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    subtitle: string;
    /**
     * URI do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    uri: string;
    /**
     * Tipo do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    type: string;
    /**
     * URL da foto do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    photo: string;
    /**
     * Cor primária do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    colorOne: string;
    /**
     * Cor secundária do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    colorTwo: string;
    /**
     * Descrição do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    description: string;
    /**
     * Informação do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    information: string;
    /**
     * Informações do evento enviados por email
     * @type {string}
     * @memberof ResponseEventDto
     */
    informationEmail: string;
    /**
     * Vídeo do evento
     * @type {string}
     * @memberof ResponseEventDto
     */
    video: string;
    /**
     * Redirecionamento depois que preencher os participantes
     * @type {string}
     * @memberof ResponseEventDto
     */
    redirect: string;
    /**
     * Link para acionar conversa/grupo no whatsApp na página de obrigado
     * @type {string}
     * @memberof ResponseEventDto
     */
    whatsappLink: string;
    /**
     * Link para acionar conversa/grupo no telegram na página de obrigado
     * @type {string}
     * @memberof ResponseEventDto
     */
    telegramLink: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseEventDto
     */
    status: ResponseEventDtoStatusEnum;
    /**
     * Data e hora de inicio do evento 
     * @type {Date}
     * @memberof ResponseEventDto
     */
    startAt: Date;
    /**
     * Data e hora de fim do evento
     * @type {Date}
     * @memberof ResponseEventDto
     */
    endAt: Date;
    /**
     * Data e hora de inicio do evento 
     * @type {Date}
     * @memberof ResponseEventDto
     */
    startPublishAt: Date;
    /**
     * Data e hora de fim do evento
     * @type {Date}
     * @memberof ResponseEventDto
     */
    endPublishAt: Date;
    /**
     * Data de criação do evento
     * @type {Date}
     * @memberof ResponseEventDto
     */
    createdAt: Date;
    /**
     * Data de atualização do evento
     * @type {Date}
     * @memberof ResponseEventDto
     */
    updatedAt: Date;
    /**
     * Data de exclusão do evento (se aplicável)
     * @type {Date}
     * @memberof ResponseEventDto
     */
    deletedAt: Date;
}


/**
 * @export
 */
export const ResponseEventDtoStatusEnum = {
    Enable: 'ENABLE',
    Disable: 'DISABLE'
} as const;
export type ResponseEventDtoStatusEnum = typeof ResponseEventDtoStatusEnum[keyof typeof ResponseEventDtoStatusEnum];


/**
 * Check if a given object implements the ResponseEventDto interface.
 */
export function instanceOfResponseEventDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "sequential" in value;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "subtitle" in value;
    isInstance = isInstance && "uri" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "photo" in value;
    isInstance = isInstance && "colorOne" in value;
    isInstance = isInstance && "colorTwo" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "information" in value;
    isInstance = isInstance && "informationEmail" in value;
    isInstance = isInstance && "video" in value;
    isInstance = isInstance && "redirect" in value;
    isInstance = isInstance && "whatsappLink" in value;
    isInstance = isInstance && "telegramLink" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "startAt" in value;
    isInstance = isInstance && "endAt" in value;
    isInstance = isInstance && "startPublishAt" in value;
    isInstance = isInstance && "endPublishAt" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "deletedAt" in value;

    return isInstance;
}

export function ResponseEventDtoFromJSON(json: any): ResponseEventDto {
    return ResponseEventDtoFromJSONTyped(json, false);
}

export function ResponseEventDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseEventDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sequential': json['sequential'],
        'accountId': json['accountId'],
        'userId': json['userId'],
        'name': json['name'],
        'subtitle': json['subtitle'],
        'uri': json['uri'],
        'type': json['type'],
        'photo': json['photo'],
        'colorOne': json['colorOne'],
        'colorTwo': json['colorTwo'],
        'description': json['description'],
        'information': json['information'],
        'informationEmail': json['informationEmail'],
        'video': json['video'],
        'redirect': json['redirect'],
        'whatsappLink': json['whatsappLink'],
        'telegramLink': json['telegramLink'],
        'status': json['status'],
        'startAt': (new Date(json['startAt'])),
        'endAt': (new Date(json['endAt'])),
        'startPublishAt': (new Date(json['startPublishAt'])),
        'endPublishAt': (new Date(json['endPublishAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': (new Date(json['deletedAt'])),
    };
}

export function ResponseEventDtoToJSON(value?: ResponseEventDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sequential': value.sequential,
        'accountId': value.accountId,
        'userId': value.userId,
        'name': value.name,
        'subtitle': value.subtitle,
        'uri': value.uri,
        'type': value.type,
        'photo': value.photo,
        'colorOne': value.colorOne,
        'colorTwo': value.colorTwo,
        'description': value.description,
        'information': value.information,
        'informationEmail': value.informationEmail,
        'video': value.video,
        'redirect': value.redirect,
        'whatsappLink': value.whatsappLink,
        'telegramLink': value.telegramLink,
        'status': value.status,
        'startAt': (value.startAt.toISOString()),
        'endAt': (value.endAt.toISOString()),
        'startPublishAt': (value.startPublishAt.toISOString()),
        'endPublishAt': (value.endPublishAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'deletedAt': (value.deletedAt.toISOString()),
    };
}

