/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEventConfigDto
 */
export interface UpdateEventConfigDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateEventConfigDto
     */
    type: UpdateEventConfigDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventConfigDto
     */
    status: UpdateEventConfigDtoStatusEnum;
}


/**
 * @export
 */
export const UpdateEventConfigDtoTypeEnum = {
    PrintAutomatic: 'PRINT_AUTOMATIC',
    SkipStepDocument: 'SKIP_STEP_DOCUMENT',
    Award: 'AWARD'
} as const;
export type UpdateEventConfigDtoTypeEnum = typeof UpdateEventConfigDtoTypeEnum[keyof typeof UpdateEventConfigDtoTypeEnum];

/**
 * @export
 */
export const UpdateEventConfigDtoStatusEnum = {
    Enable: 'ENABLE',
    Disable: 'DISABLE'
} as const;
export type UpdateEventConfigDtoStatusEnum = typeof UpdateEventConfigDtoStatusEnum[keyof typeof UpdateEventConfigDtoStatusEnum];


/**
 * Check if a given object implements the UpdateEventConfigDto interface.
 */
export function instanceOfUpdateEventConfigDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function UpdateEventConfigDtoFromJSON(json: any): UpdateEventConfigDto {
    return UpdateEventConfigDtoFromJSONTyped(json, false);
}

export function UpdateEventConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEventConfigDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'status': json['status'],
    };
}

export function UpdateEventConfigDtoToJSON(value?: UpdateEventConfigDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'status': value.status,
    };
}

