/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAddressDto
 */
export interface UpdateAddressDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressDto
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressDto
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressDto
     */
    country: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateAddressDto
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateAddressDto
     */
    label: string;
}

/**
 * Check if a given object implements the UpdateAddressDto interface.
 */
export function instanceOfUpdateAddressDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "street" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "isActive" in value;
    isInstance = isInstance && "label" in value;

    return isInstance;
}

export function UpdateAddressDtoFromJSON(json: any): UpdateAddressDto {
    return UpdateAddressDtoFromJSONTyped(json, false);
}

export function UpdateAddressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAddressDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'street': json['street'],
        'city': json['city'],
        'state': json['state'],
        'country': json['country'],
        'isActive': json['isActive'],
        'label': json['label'],
    };
}

export function UpdateAddressDtoToJSON(value?: UpdateAddressDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'street': value.street,
        'city': value.city,
        'state': value.state,
        'country': value.country,
        'isActive': value.isActive,
        'label': value.label,
    };
}

