/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateUserDocumentDto } from './UpdateUserDocumentDto';
import {
    UpdateUserDocumentDtoFromJSON,
    UpdateUserDocumentDtoFromJSONTyped,
    UpdateUserDocumentDtoToJSON,
} from './UpdateUserDocumentDto';

/**
 * 
 * @export
 * @interface UpdateDocumentDto
 */
export interface UpdateDocumentDto {
    /**
     * Número do documento
     * @type {string}
     * @memberof UpdateDocumentDto
     */
    number: string;
    /**
     * Tipo do documento
     * @type {string}
     * @memberof UpdateDocumentDto
     */
    type: string;
    /**
     * Path do documento no computador
     * @type {string}
     * @memberof UpdateDocumentDto
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDocumentDto
     */
    status: UpdateDocumentDtoStatusEnum;
    /**
     * Data e hora da última atualização no documento
     * @type {Date}
     * @memberof UpdateDocumentDto
     */
    updatedAt: Date;
    /**
     * Data e hora da exclusão do documento
     * @type {Date}
     * @memberof UpdateDocumentDto
     */
    deletedAt: Date;
    /**
     * 
     * @type {UpdateUserDocumentDto}
     * @memberof UpdateDocumentDto
     */
    userDocument: UpdateUserDocumentDto;
}


/**
 * @export
 */
export const UpdateDocumentDtoStatusEnum = {
    Sent: 'SENT',
    AwaitingVerification: 'AWAITING_VERIFICATION',
    Verified: 'VERIFIED'
} as const;
export type UpdateDocumentDtoStatusEnum = typeof UpdateDocumentDtoStatusEnum[keyof typeof UpdateDocumentDtoStatusEnum];


/**
 * Check if a given object implements the UpdateDocumentDto interface.
 */
export function instanceOfUpdateDocumentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "filePath" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "deletedAt" in value;
    isInstance = isInstance && "userDocument" in value;

    return isInstance;
}

export function UpdateDocumentDtoFromJSON(json: any): UpdateDocumentDto {
    return UpdateDocumentDtoFromJSONTyped(json, false);
}

export function UpdateDocumentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDocumentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'type': json['type'],
        'filePath': json['filePath'],
        'status': json['status'],
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': (new Date(json['deletedAt'])),
        'userDocument': UpdateUserDocumentDtoFromJSON(json['userDocument']),
    };
}

export function UpdateDocumentDtoToJSON(value?: UpdateDocumentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'type': value.type,
        'filePath': value.filePath,
        'status': value.status,
        'updatedAt': (value.updatedAt.toISOString()),
        'deletedAt': (value.deletedAt.toISOString()),
        'userDocument': UpdateUserDocumentDtoToJSON(value.userDocument),
    };
}

