/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAccountUserDto
 */
export interface UpdateAccountUserDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountUserDto
     */
    status: UpdateAccountUserDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountUserDto
     */
    type: UpdateAccountUserDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountUserDto
     */
    position: string;
}


/**
 * @export
 */
export const UpdateAccountUserDtoStatusEnum = {
    Enabled: 'ENABLED',
    Disabled: 'DISABLED',
    WaitingApproval: 'WAITING_APPROVAL'
} as const;
export type UpdateAccountUserDtoStatusEnum = typeof UpdateAccountUserDtoStatusEnum[keyof typeof UpdateAccountUserDtoStatusEnum];

/**
 * @export
 */
export const UpdateAccountUserDtoTypeEnum = {
    Team: 'TEAM',
    Student: 'STUDENT'
} as const;
export type UpdateAccountUserDtoTypeEnum = typeof UpdateAccountUserDtoTypeEnum[keyof typeof UpdateAccountUserDtoTypeEnum];


/**
 * Check if a given object implements the UpdateAccountUserDto interface.
 */
export function instanceOfUpdateAccountUserDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "position" in value;

    return isInstance;
}

export function UpdateAccountUserDtoFromJSON(json: any): UpdateAccountUserDto {
    return UpdateAccountUserDtoFromJSONTyped(json, false);
}

export function UpdateAccountUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'type': json['type'],
        'position': json['position'],
    };
}

export function UpdateAccountUserDtoToJSON(value?: UpdateAccountUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'type': value.type,
        'position': value.position,
    };
}

