/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserDocumentDto
 */
export interface UpdateUserDocumentDto {
    /**
     * URL da foto
     * @type {string}
     * @memberof UpdateUserDocumentDto
     */
    photo?: string;
    /**
     * Indica se está ativo
     * @type {boolean}
     * @memberof UpdateUserDocumentDto
     */
    isActive?: boolean;
    /**
     * Data e hora da última atualização no documento
     * @type {Date}
     * @memberof UpdateUserDocumentDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UpdateUserDocumentDto interface.
 */
export function instanceOfUpdateUserDocumentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function UpdateUserDocumentDtoFromJSON(json: any): UpdateUserDocumentDto {
    return UpdateUserDocumentDtoFromJSONTyped(json, false);
}

export function UpdateUserDocumentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserDocumentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'photo': !exists(json, 'photo') ? undefined : json['photo'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function UpdateUserDocumentDtoToJSON(value?: UpdateUserDocumentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'photo': value.photo,
        'isActive': value.isActive,
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

