/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDocumentParticipantDto
 */
export interface UpdateDocumentParticipantDto {
    /**
     * Número do documento
     * @type {string}
     * @memberof UpdateDocumentParticipantDto
     */
    number: string;
    /**
     * Tipo do documento
     * @type {string}
     * @memberof UpdateDocumentParticipantDto
     */
    type: string;
    /**
     * Path do documento no computador
     * @type {string}
     * @memberof UpdateDocumentParticipantDto
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDocumentParticipantDto
     */
    status: UpdateDocumentParticipantDtoStatusEnum;
    /**
     * Data e hora da última atualização no documento
     * @type {Date}
     * @memberof UpdateDocumentParticipantDto
     */
    updatedAt: Date;
    /**
     * Data e hora da exclusão do documento
     * @type {Date}
     * @memberof UpdateDocumentParticipantDto
     */
    deletedAt: Date;
}


/**
 * @export
 */
export const UpdateDocumentParticipantDtoStatusEnum = {
    Sent: 'SENT',
    AwaitingVerification: 'AWAITING_VERIFICATION',
    Verified: 'VERIFIED'
} as const;
export type UpdateDocumentParticipantDtoStatusEnum = typeof UpdateDocumentParticipantDtoStatusEnum[keyof typeof UpdateDocumentParticipantDtoStatusEnum];


/**
 * Check if a given object implements the UpdateDocumentParticipantDto interface.
 */
export function instanceOfUpdateDocumentParticipantDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "filePath" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "deletedAt" in value;

    return isInstance;
}

export function UpdateDocumentParticipantDtoFromJSON(json: any): UpdateDocumentParticipantDto {
    return UpdateDocumentParticipantDtoFromJSONTyped(json, false);
}

export function UpdateDocumentParticipantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDocumentParticipantDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'type': json['type'],
        'filePath': json['filePath'],
        'status': json['status'],
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': (new Date(json['deletedAt'])),
    };
}

export function UpdateDocumentParticipantDtoToJSON(value?: UpdateDocumentParticipantDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'type': value.type,
        'filePath': value.filePath,
        'status': value.status,
        'updatedAt': (value.updatedAt.toISOString()),
        'deletedAt': (value.deletedAt.toISOString()),
    };
}

