/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEventParticipantStatusDto
 */
export interface UpdateEventParticipantStatusDto {
    /**
     * Status do usuário no evento
     * @type {string}
     * @memberof UpdateEventParticipantStatusDto
     */
    status: UpdateEventParticipantStatusDtoStatusEnum;
}


/**
 * @export
 */
export const UpdateEventParticipantStatusDtoStatusEnum = {
    Checkin: 'CHECKIN',
    Checkout: 'CHECKOUT',
    Pending: 'PENDING'
} as const;
export type UpdateEventParticipantStatusDtoStatusEnum = typeof UpdateEventParticipantStatusDtoStatusEnum[keyof typeof UpdateEventParticipantStatusDtoStatusEnum];


/**
 * Check if a given object implements the UpdateEventParticipantStatusDto interface.
 */
export function instanceOfUpdateEventParticipantStatusDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function UpdateEventParticipantStatusDtoFromJSON(json: any): UpdateEventParticipantStatusDto {
    return UpdateEventParticipantStatusDtoFromJSONTyped(json, false);
}

export function UpdateEventParticipantStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEventParticipantStatusDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function UpdateEventParticipantStatusDtoToJSON(value?: UpdateEventParticipantStatusDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

