/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEventTicketDto
 */
export interface UpdateEventTicketDto {
    /**
     * Nome do participante
     * @type {string}
     * @memberof UpdateEventTicketDto
     */
    name: string;
    /**
     * Preço do ingresso
     * @type {number}
     * @memberof UpdateEventTicketDto
     */
    price: number;
    /**
     * Preço antes do desconto
     * @type {number}
     * @memberof UpdateEventTicketDto
     */
    priceBefore: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventTicketDto
     */
    status: UpdateEventTicketDtoStatusEnum;
    /**
     * Cor do ingresso
     * @type {string}
     * @memberof UpdateEventTicketDto
     */
    color?: string;
    /**
     * Número de convidados
     * @type {number}
     * @memberof UpdateEventTicketDto
     */
    guest?: number;
    /**
     * Data de criação
     * @type {Date}
     * @memberof UpdateEventTicketDto
     */
    createdAt: Date;
    /**
     * Data de atualização
     * @type {Date}
     * @memberof UpdateEventTicketDto
     */
    updatedAt: Date;
    /**
     * Data de exclusão (se aplicável)
     * @type {Date}
     * @memberof UpdateEventTicketDto
     */
    deletedAt: Date;
}


/**
 * @export
 */
export const UpdateEventTicketDtoStatusEnum = {
    Enable: 'ENABLE',
    Disable: 'DISABLE'
} as const;
export type UpdateEventTicketDtoStatusEnum = typeof UpdateEventTicketDtoStatusEnum[keyof typeof UpdateEventTicketDtoStatusEnum];


/**
 * Check if a given object implements the UpdateEventTicketDto interface.
 */
export function instanceOfUpdateEventTicketDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "priceBefore" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "deletedAt" in value;

    return isInstance;
}

export function UpdateEventTicketDtoFromJSON(json: any): UpdateEventTicketDto {
    return UpdateEventTicketDtoFromJSONTyped(json, false);
}

export function UpdateEventTicketDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEventTicketDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
        'priceBefore': json['priceBefore'],
        'status': json['status'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'guest': !exists(json, 'guest') ? undefined : json['guest'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': (new Date(json['deletedAt'])),
    };
}

export function UpdateEventTicketDtoToJSON(value?: UpdateEventTicketDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'price': value.price,
        'priceBefore': value.priceBefore,
        'status': value.status,
        'color': value.color,
        'guest': value.guest,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'deletedAt': (value.deletedAt.toISOString()),
    };
}

