/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEventParticipantDto
 */
export interface UpdateEventParticipantDto {
    /**
     * ID do ingresso associada ao participante (UUID)
     * @type {string}
     * @memberof UpdateEventParticipantDto
     */
    eventTicketId: string;
    /**
     * ID do usuário participante
     * @type {string}
     * @memberof UpdateEventParticipantDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventParticipantDto
     */
    status: UpdateEventParticipantDtoStatusEnum;
    /**
     * Participant synchronized with local db
     * @type {boolean}
     * @memberof UpdateEventParticipantDto
     */
    isSynchronized: boolean;
}


/**
 * @export
 */
export const UpdateEventParticipantDtoStatusEnum = {
    AwaitingPayment: 'AWAITING_PAYMENT',
    CheckInEarly: 'CHECK_IN_EARLY',
    CheckIn: 'CHECK_IN',
    CheckOut: 'CHECK_OUT',
    Canceled: 'CANCELED',
    Enable: 'ENABLE'
} as const;
export type UpdateEventParticipantDtoStatusEnum = typeof UpdateEventParticipantDtoStatusEnum[keyof typeof UpdateEventParticipantDtoStatusEnum];


/**
 * Check if a given object implements the UpdateEventParticipantDto interface.
 */
export function instanceOfUpdateEventParticipantDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eventTicketId" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "isSynchronized" in value;

    return isInstance;
}

export function UpdateEventParticipantDtoFromJSON(json: any): UpdateEventParticipantDto {
    return UpdateEventParticipantDtoFromJSONTyped(json, false);
}

export function UpdateEventParticipantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEventParticipantDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventTicketId': json['eventTicketId'],
        'userId': json['userId'],
        'status': json['status'],
        'isSynchronized': json['isSynchronized'],
    };
}

export function UpdateEventParticipantDtoToJSON(value?: UpdateEventParticipantDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventTicketId': value.eventTicketId,
        'userId': value.userId,
        'status': value.status,
        'isSynchronized': value.isSynchronized,
    };
}

