/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDocumentResponseDto
 */
export interface UserDocumentResponseDto {
    /**
     * ID do UserDocument (UUID)
     * @type {string}
     * @memberof UserDocumentResponseDto
     */
    id: string;
    /**
     * ID do usuário (UUID)
     * @type {string}
     * @memberof UserDocumentResponseDto
     */
    userId: string;
    /**
     * ID do documento (UUID)
     * @type {string}
     * @memberof UserDocumentResponseDto
     */
    documentId: string;
    /**
     * Indica se está ativo
     * @type {boolean}
     * @memberof UserDocumentResponseDto
     */
    isActive: boolean;
    /**
     * URL da foto
     * @type {string}
     * @memberof UserDocumentResponseDto
     */
    photo: string;
    /**
     * Data e hora da criação do UserDocument
     * @type {Date}
     * @memberof UserDocumentResponseDto
     */
    createdAt: Date;
    /**
     * Data e hora da última atualização no UserDocument
     * @type {Date}
     * @memberof UserDocumentResponseDto
     */
    updatedAt: Date;
    /**
     * Data e hora da exclusão do UserDocument
     * @type {Date}
     * @memberof UserDocumentResponseDto
     */
    deletedAt: Date;
}

/**
 * Check if a given object implements the UserDocumentResponseDto interface.
 */
export function instanceOfUserDocumentResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "documentId" in value;
    isInstance = isInstance && "isActive" in value;
    isInstance = isInstance && "photo" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "deletedAt" in value;

    return isInstance;
}

export function UserDocumentResponseDtoFromJSON(json: any): UserDocumentResponseDto {
    return UserDocumentResponseDtoFromJSONTyped(json, false);
}

export function UserDocumentResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDocumentResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'documentId': json['documentId'],
        'isActive': json['isActive'],
        'photo': json['photo'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': (new Date(json['deletedAt'])),
    };
}

export function UserDocumentResponseDtoToJSON(value?: UserDocumentResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'documentId': value.documentId,
        'isActive': value.isActive,
        'photo': value.photo,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'deletedAt': (value.deletedAt.toISOString()),
    };
}

