/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInitialSubscribe
 */
export interface UserInitialSubscribe {
    /**
     * 
     * @type {string}
     * @memberof UserInitialSubscribe
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserInitialSubscribe
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserInitialSubscribe
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserInitialSubscribe
     */
    countryCodePhone: string;
    /**
     * 
     * @type {string}
     * @memberof UserInitialSubscribe
     */
    areaCodePhone: string;
    /**
     * 
     * @type {string}
     * @memberof UserInitialSubscribe
     */
    phoneNumber: string;
}

/**
 * Check if a given object implements the UserInitialSubscribe interface.
 */
export function instanceOfUserInitialSubscribe(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "countryCodePhone" in value;
    isInstance = isInstance && "areaCodePhone" in value;
    isInstance = isInstance && "phoneNumber" in value;

    return isInstance;
}

export function UserInitialSubscribeFromJSON(json: any): UserInitialSubscribe {
    return UserInitialSubscribeFromJSONTyped(json, false);
}

export function UserInitialSubscribeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInitialSubscribe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
        'countryCodePhone': json['countryCodePhone'],
        'areaCodePhone': json['areaCodePhone'],
        'phoneNumber': json['phoneNumber'],
    };
}

export function UserInitialSubscribeToJSON(value?: UserInitialSubscribe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'password': value.password,
        'countryCodePhone': value.countryCodePhone,
        'areaCodePhone': value.areaCodePhone,
        'phoneNumber': value.phoneNumber,
    };
}

