/* tslint:disable */
/* eslint-disable */
/**
 * Invicta API DEV
 * Utilize essa documentação para realizar integração com o nosso sistema
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateOtpDto
 */
export interface ValidateOtpDto {
    /**
     * Senha OTP
     * @type {string}
     * @memberof ValidateOtpDto
     */
    number: string;
    /**
     * HASH
     * @type {string}
     * @memberof ValidateOtpDto
     */
    hash: string;
}

/**
 * Check if a given object implements the ValidateOtpDto interface.
 */
export function instanceOfValidateOtpDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "hash" in value;

    return isInstance;
}

export function ValidateOtpDtoFromJSON(json: any): ValidateOtpDto {
    return ValidateOtpDtoFromJSONTyped(json, false);
}

export function ValidateOtpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateOtpDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'hash': json['hash'],
    };
}

export function ValidateOtpDtoToJSON(value?: ValidateOtpDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'hash': value.hash,
    };
}

